using System.Collections.Generic;

namespace UC_MapPainter
{
    public static class ObjectNames
    {
        public static readonly Dictionary<int, string> Names = new Dictionary<int, string>
        {
            { 0, "End of data" },
            { 1, "Street Lamp" },
            { 2, "Traffic LightEntry" },
            { 3, "Small Traffic LightEntry" },
            { 4, "Single Gas Pump" },
            { 5, "Double Gas Pump" },
            { 6, "Awaken Sign" },
            { 7, "Vote Bane Sign" },
            { 8, "Gas Price Sign" },
            { 9, "Silvery Moon Sign" },
            { 10, "Gas Sign" },
            { 11, "Street Lamp" },
            { 12, "Motel Sign" },
            { 13, "Metal Walkway 1" },
            { 14, "Metal Walkway 2" },
            { 15, "Metal Walkway 3" },
            { 16, "Metal Walkway 4" },
            { 17, "Metal Walkway 5" },
            { 18, "Tyres Sign" },
            { 19, "Green Canopy 1" },
            { 20, "Damaged Green Canopy 1" },
            { 21, "Green Canopy 2" },
            { 22, "Damaged Green Canopy 2" },
            { 23, "Diner Sign" },
            { 24, "Damaged Green Canopy 3" },
            { 25, "Silvery Moon Sign 2" },
            { 26, "Motel Sign 2" },
            { 27, "Wild Cat Van" },
            { 28, "Wild Cat Crate" },
            { 29, "Metal Walkway Corner" },
            { 30, "Pot Plant" },
            { 31, "Liquors Sign" },
            { 32, "Demon Gas Pipe" },
            { 33, "Trash Can" },
            { 34, "Tree 1" },
            { 35, "Tree 2" },
            { 36, "Key" },
            { 37, "Wooden Post" },
            { 38, "Weed" },
            { 39, "Constitution (Treasure)" },
            { 40, "Gas Cylinder" },
            { 41, "Stairs" },
            { 42, "4-Way Street Lamp" },
            { 43, "Side Step" },
            { 44, "Metal Lift" },
            { 45, "Terminal Sign" },
            { 46, "Bush 1" },
            { 47, "Liberty Statue" },
            { 48, "USA Flag" },
            { 49, "Greenhouse" },
            { 50, "Estate Archway" },
            { 51, "Wood Post & Cable" },
            { 52, "Street Sign (Blue)" },
            { 53, "Speed Limit Sign" },
            { 54, "Right Turn Sign" },
            { 55, "Do Not Enter Sign" },
            { 56, "Le Grande Sign" },
            { 57, "Rail Sign 2" },
            { 58, "Tree 3" },
            { 59, "Tree 4" },
            { 60, "Railway Stand" },
            { 61, "Boombox" },
            { 62, "Lion Statue" },
            { 63, "Motomo Sign" },
            { 64, "Choke Sign" },
            { 65, "Buy Cigarette Sign" },
            { 66, "Take Away Sign" },
            { 67, "Road Cone" },
            { 68, "Ala Mode Sign" },
            { 69, "Planter Box" },
            { 70, "Brown Pedestal" },
            { 71, "Stamina (Treasure)" },
            { 72, "Bush 2" },
            { 73, "Building Top 1" },
            { 74, "Helicopter Body" },
            { 75, "Helicopter Rotor" },
            { 76, "Soda Can" },
            { 77, "Marble Archway" },
            { 78, "Tree 5" },
            { 79, "Building Top 2" },
            { 80, "Side Step" },
            { 81, "Reflexes (Treasure)" },
            { 82, "Nude Sign" },
            { 83, "Filing Cabinet" },
            { 84, "Shock Sign" },
            { 85, "Wrought Iron Gate" },
            { 86, "Wrought Iron Gate Door" },
            { 87, "Van Tyre" },
            { 88, "Civilian Van" },
            { 89, "Park Bench" },
            { 90, "SUV" },
            { 91, "Police SUV" },
            { 92, "Building Top 3" },
            { 93, "Corner Desk" },
            { 94, "Strength (Treasure)" },
            { 95, "Café Chair" },
            { 96, "Café Table" },
            { 97, "Cross Tombstone" },
            { 98, "Round Tombstone" },
            { 99, "Doors 1" },
            { 100, "Fuel Meter" },
            { 101, "Single Sofa" },
            { 102, "Brown Coffee Table" },
            { 103, "TV" },
            { 104, "Lamp" },
            { 105, "Double Sofa" },
            { 106, "Building Top 4" },
            { 107, "Choke Floor Sign" },
            { 108, "Civilian Sedan" },
            { 109, "Metal Walkway 6" },
            { 110, "Long Table" },
            { 111, "Pool Sign" },
            { 112, "Computer" },
            { 113, "Flood LightEntry" },
            { 114, "Tugboat" },
            { 115, "Stone Archway" },
            { 116, "Payphone" },
            { 117, "Doors 2" },
            { 118, "Stone Archway Top" },
            { 119, "Orange Sign" },
            { 120, "M16 - Pickup" },
            { 121, "Revolver" },
            { 122, "Car Shell" },
            { 123, "Brown Canopy" },
            { 124, "Colored Lights" },
            { 125, "Motel Sign" },
            { 126, "Brown Office Chair" },
            { 127, "Shotgun - Pickup" },
            { 128, "Pool Table" },
            { 129, "Crate Large" },
            { 130, "Crate Small" },
            { 131, "Soft Top Sedan" },
            { 132, "Satellite Dish" },
            { 133, "UCPD Sign" },
            { 134, "Square Bin" },
            { 135, "Police Flagpole" },
            { 136, "Reflexes (Treasure)" },
            { 137, "Repent Sign" },
            { 138, "Motorbike Wheel" },
            { 139, "Book Case" },
            { 140, "Bike Seat" },
            { 141, "Oil Barrel" },
            { 142, "Med Pack" },
            { 143, "Pistol" },
            { 144, "Napkin" },
            { 145, "Explosive Barrel" },
            { 146, "Phone box" },
            { 147, "Target Practice Dummy" },
            { 148, "Police Roof LightEntry" },
            { 149, "Palm Tree" },
            { 150, "Police Sedan" },
            { 151, "Searchlight" },
            { 152, "Ivy" },
            { 153, "Ivy 2" },
            { 154, "Doors 3" },
            { 155, "Taxi" },
            { 156, "Danger Barrier" },
            { 157, "Green Switch" },
            { 158, "Brown Stool" },
            { 159, "Ambulance" },
            { 160, "Funnel" },
            { 161, "Men Working Sign" },
            { 162, "Stop Sign" },
            { 163, "Dead End Sign" },
            { 164, "Danger Sign" },
            { 165, "Road Barrier" },
            { 166, "Knife" },
            { 167, "Explosives - Pickup" },
            { 168, "Grenade" },
            { 169, "Blue Mailbox" },
            { 170, "Rail Pillar" },
            { 171, "Rail Track" },
            { 172, "Sniper Rifle" },
            { 173, "Curve Rail" },
            { 174, "Straight Rail" },
            { 175, "Rail barrier" },
            { 176, "Railing" },
            { 177, "AK-47" },
            { 178, "Laser Box" },
            { 179, "Bar Sign" },
            { 180, "Pool Chair" },
            { 181, "Bane Gate Left" },
            { 182, "Bane Gate Right" },
            { 183, "Cure Rail Barrier" },
            { 184, "Bed" },
            { 185, "Double Brown Desk" },
            { 186, "Single Brown desk" },
            { 187, "Corner Brown Desk" },
            { 188, "Mine" },
            { 189, "Male Statue 2" },
            { 190, "Wall LightEntry" },
            { 191, "Female Statue" },
            { 192, "Male Statue" },
            { 193, "Pipe 1" },
            { 194, "Pipe 2" },
            { 195, "Pipe 3" },
            { 196, "Pipe 4" },
            { 197, "Pipe 5" },
            { 198, "Pipe 6" },
            { 199, "Pipe 7" },
            { 200, "Parasol" },
            { 201, "Roomba" },
            { 202, "Inflatable Chair" },
            { 203, "Weeds 2" },
            { 204, "Diving Board" },
            { 205, "Baseball Bat" },
            { 206, "Aerial" },
            { 207, "Water Tower 1" },
            { 208, "Pot Plant 2" },
            { 209, "Blue Canopy" },
            { 210, "Double Blue Canopy" },
            { 211, "Corner Blue Canopy" },
            { 212, "Pink Flowers" },
            { 213, "Chimney" },
            { 214, "Vent" },
            { 215, "Chimney 2" },
            { 216, "Red Switch" },
            { 217, "Washing Line" },
            { 218, "Powerline" },
            { 219, "Winch" },
            { 220, "Sedan Wheel" },
            { 221, "Dumpster" },
            { 222, "Water Tower 2" },
            { 223, "Hotel Sign" },
            { 224, "Vent Long" },
            { 225, "Vent 2" },
            { 226, "Skylight 1" },
            { 227, "Skylight 2" },
            { 228, "Fire Hydrant" },
            { 229, "Wall Garden LightEntry" },
            { 230, "Ground Garden LightEntry" },
            { 231, "Wildcat Topiary" },
            { 232, "Red Folder" },
            { 233, "Disk" },
            { 234, "Wall Mounted M16" },
            { 235, "Disco LightEntry" },
            { 236, "Liquor Cabinet" },
            { 237, "VHS Tape" },
            { 238, "Police Motorbike" },
            { 239, "Weed Away" },
            { 240, "Round Hedge" },
            { 241, "Brown Yellow Canopy" },
            { 242, "Hot Dog Stand" },
            { 243, "Rifle" },
            { 244, "Doors 4" },
            { 245, "Missile" },
            { 246, "Red Canopy" },
            { 247, "Marble Pillar Top" },
            { 248, "Xpresso Sign" },
            { 249, "Marble Pillar" },
            { 250, "Marble Plant" },
            { 251, "Marble Plant 2" },
            { 252, "Marble Pedestal" },
            { 253, "Shotgun Ammo" },
            { 254, "M16 Ammo" },
            { 255, "Pistol Ammo" }
        };

        public static string GetName(int id)
        {
            return Names.TryGetValue(id, out var name) ? name : "Unknown";
        }
    }
}
